function tables = make_additional_tables(selection,repo_root,output_dir)
%MAKE_ADDITIONAL_TABLES Export Tables 4-8 from completed paper checkpoints.
arguments
    selection (1,1) string {mustBeMember(selection, ...
        ["sensitivity","ablation","conditioning","runtime"])}
    repo_root char = fileparts(fileparts(mfilename('fullpath')))
    output_dir char = fullfile(repo_root,'results','tables','paper')
end
if ~isfolder(output_dir), mkdir(output_dir); end
tables = struct();
switch selection
    case "sensitivity"
        config = config_sensitivity(3,36500);
        experiment = load_complete(fullfile(repo_root,config.output_file));
        summary = summarize_alpha_epsilon_sensitivity(experiment);
        assert(all(summary.completed_count(:)==100), ...
            'Expected 100 repetitions for every sensitivity pair.');
        names = {'alpha','epsilon_0_005','epsilon_0_01','epsilon_0_02', ...
            'epsilon_0_05','epsilon_0_1'};
        assert(isequal(summary.alpha_values,[10 20 30 50 80]) && ...
            isequal(summary.epsilon_values,[0.005 0.01 0.02 0.05 0.1]), ...
            'Sensitivity axes do not match the paper.');
        tables.table4 = array2table([summary.alpha_values(:), ...
            100*summary.success_rate],'VariableNames',names);
        tables.table7a = array2table([summary.alpha_values(:), ...
            summary.mean_distance_to_vstar],'VariableNames',names);
        tables.table7b = array2table([summary.alpha_values(:), ...
            summary.mean_feasibility_error],'VariableNames',names);
    case "ablation"
        configs = config_thomson();
        positive = configs(arrayfun(@(c)c.problem.metadata.k==56,configs));
        zero = config_noise_ablation(47000);
        a = load_complete(fullfile(repo_root,positive.output_file));
        b = load_complete(fullfile(repo_root,zero.output_file));
        assert(isequal(a.initial_seeds,b.initial_seeds) && ...
            isequal(a.solver_seeds,b.solver_seeds) && ...
            isequal(a.base_initializations,b.base_initializations), ...
            'The two ablation arms must use paired seeds and initial particles.');
        rows = zeros(2,8);
        experiments = {a,b};
        for i=1:2
            runs = experiments{i}.results(1,:);
            rows(i,:) = [experiments{i}.solver_config.sigma_indep, ...
                numel(runs),100*mean(cellfun(@(r)double(r.success),runs)), ...
                mean(cellfun(@(r)r.relative_objective_error,runs)), ...
                mean(cellfun(@(r)r.feasibility_error,runs)), ...
                mean(cellfun(@(r)r.l1_feasibility,runs)), ...
                mean(cellfun(@(r)r.iterations,runs)), ...
                mean(cellfun(@(r)r.runtime,runs))];
        end
        tables.table5 = array2table(rows,'VariableNames', ...
            {'sigma_indep','repetitions','success_percent', ...
            'mean_relative_error','mean_sqrt_G','mean_l1_feasibility', ...
            'mean_iterations','mean_runtime_seconds'});
    case "conditioning"
        saved = load(fullfile(repo_root,'results','diagnostics','conditioning', ...
            'k470_conditioning_reps1_3.mat'),'diagnostic');
        diagnostic = saved.diagnostic;
        validate_conditioning_cache(diagnostic,repo_root);
        condition_values = cellfun(@(r)r.full_cond2(:), ...
            diagnostic.run_diagnostics,'UniformOutput',false);
        minimum_values = cellfun(@(r)r.full_sigma_min(:), ...
            diagnostic.run_diagnostics,'UniformOutput',false);
        condition_values = vertcat(condition_values{:});
        minimum_values = vertcat(minimum_values{:});
        assert(numel(condition_values)==300000 && ...
            numel(minimum_values)==300000, ...
            'Expected three runs of 50 particles and 2000 steps.');
        finite_values = sort(condition_values(isfinite(condition_values)));
        % Match the diagnostic's interpolation rule: index 1+(n-1)*p.
        percentiles = interp1(1:numel(finite_values),finite_values, ...
            1+(numel(finite_values)-1)*[0.5 0.95 0.99]);
        quantity = ["median";"quantile_95";"quantile_99"; ...
            "count_sigma_min_below_1e_4";"count_sigma_min_below_1e_5"; ...
            "maximum_condition_number"];
        value = [percentiles(:);sum(minimum_values<1e-4); ...
            sum(minimum_values<1e-5);max(condition_values)];
        tables.table6 = table(quantity,value);
    case "runtime"
        configs = [config_simple(),config_ackley()];
        case_id = string({configs.id}).';
        values = zeros(numel(configs),5);
        for i=1:numel(configs)
            experiment = load_complete(fullfile(repo_root,configs(i).output_file));
            methods = string(experiment.methods);
            times = zeros(3,100);
            names = ["proposed","quadratic-penalty-cbo","cb2o"];
            for j=1:3
                index = find(methods==names(j));
                assert(isscalar(index),'Missing or duplicate runtime method.');
                runs = experiment.results(index,:);
                iterations = cellfun(@(r)r.iterations,runs);
                assert(all(iterations>0),'Runtime per iteration requires positive steps.');
                times(j,:) = cellfun(@(r)r.runtime,runs)./iterations;
            end
            % Compute each paired ratio before taking its median.
            values(i,:) = [median(times,2).', ...
                median(times(1,:)./times(2,:)), ...
                median(times(1,:)./times(3,:))];
        end
        tables.table8 = [table(case_id),array2table(values,'VariableNames', ...
            {'proposed_seconds_per_iteration','penalized_seconds_per_iteration', ...
            'cb2o_seconds_per_iteration','median_proposed_over_penalized', ...
            'median_proposed_over_cb2o'})];
end
names = fieldnames(tables);
for i=1:numel(names)
    writetable(tables.(names{i}),fullfile(output_dir,[names{i} '_data.csv']));
end
end

function validate_conditioning_cache(diagnostic,repo_root)
configs = config_thomson();
config = configs(arrayfun(@(c)c.problem.metadata.k==470,configs));
signature = experiment_checkpoint_signature(config);
repetitions = 1:3;
required = {'case_id','problem_metadata','master_seed', ...
    'canonical_repetitions','repetition_ids','initialization_seeds', ...
    'solver_seeds','solver_config','q','reproduction', ...
    'run_diagnostics','final_outputs'};
conditioning_match(isstruct(diagnostic) && isscalar(diagnostic) && ...
    all(isfield(diagnostic,required)),'missing diagnostic metadata');
conditioning_match(isequaln(diagnostic.case_id,config.id) && ...
    isequaln(diagnostic.problem_metadata,config.problem.metadata) && ...
    isequaln(diagnostic.master_seed,config.master_seed) && ...
    isequaln(diagnostic.canonical_repetitions,config.repetitions), ...
    'case or problem metadata');
conditioning_match(isequaln(diagnostic.repetition_ids,repetitions) && ...
    isequaln(diagnostic.initialization_seeds,signature.initial_seeds(repetitions)) && ...
    isequaln(diagnostic.solver_seeds,signature.solver_seeds(repetitions)), ...
    'repetition IDs or seeds');
conditioning_match(isequaln(diagnostic.solver_config, ...
    revision_solver_config_metadata(config.solver_config)) && ...
    isequaln(diagnostic.q,config.solver_config.gamma/config.solver_config.epsilon), ...
    'solver settings');

production_file = fullfile(repo_root,config.output_file);
conditioning_match(isfile(production_file),'missing production checkpoint');
production = load_complete(production_file);
conditioning_match(all(isfield(production, ...
    {'signature','id','methods','initial_seeds','solver_seeds','completed_repetitions'})) && ...
    isequaln(production.signature,signature) && ...
    isequaln(production.id,config.id) && ...
    isequaln(production.methods,config.methods) && ...
    isequaln(production.initial_seeds,signature.initial_seeds) && ...
    isequaln(production.solver_seeds,signature.solver_seeds) && ...
    production.completed_repetitions==config.repetitions && ...
    isequal(size(production.results),[1 config.repetitions]), ...
    'production checkpoint configuration');
conditioning_match(isstruct(diagnostic.reproduction) && ...
    numel(diagnostic.reproduction)==numel(repetitions) && ...
    all(isfield(diagnostic.reproduction,{'repetition','pass'})) && ...
    isequal([diagnostic.reproduction.repetition],repetitions) && ...
    all([diagnostic.reproduction.pass]) && ...
    iscell(diagnostic.run_diagnostics) && ...
    numel(diagnostic.run_diagnostics)==numel(repetitions) && ...
    iscell(diagnostic.final_outputs) && ...
    numel(diagnostic.final_outputs)==numel(repetitions), ...
    'diagnostic run records');

% Instrumentation changes runtime, so compare only the saved numerical state.
fields = {'objective_value','objective_error','relative_objective_error', ...
    'G_value','feasibility_error','l1_feasibility','iterations', ...
    'exit_reason','output_source','v_out','best_objective','best_consensus', ...
    'final_ensemble_consensus','restarts','restart_count', ...
    'concentration_event_count','best_incumbent_update_count', ...
    'initial_seed','solver_seed','repetition'};
for index=1:numel(repetitions)
    actual = diagnostic.final_outputs{index};
    expected = production.results{1,repetitions(index)};
    conditioning_match(isstruct(actual) && isscalar(actual) && ...
        isstruct(expected) && isscalar(expected) && ...
        all(isfield(actual,fields)) && all(isfield(expected,fields)), ...
        'missing final-state fields');
    for field=fields
        conditioning_match(isequaln(actual.(field{1}),expected.(field{1})), ...
            sprintf('repetition %d final field %s',repetitions(index),field{1}));
    end
    record = diagnostic.run_diagnostics{index};
    conditioning_match(isstruct(record) && isscalar(record) && ...
        all(isfield(record,{'repetition','iterations','full_cond2','full_sigma_min'})) && ...
        isequaln(record.repetition,repetitions(index)) && ...
        isequaln(record.iterations,expected.iterations) && ...
        isequal(size(record.full_cond2),[expected.iterations config.solver_config.particles]) && ...
        isequal(size(record.full_sigma_min),size(record.full_cond2)), ...
        'conditioning sample dimensions');
end
end

function conditioning_match(matches,detail)
assert(matches,'make_additional_tables:ConditioningCacheMismatch', ...
    ['Conditioning diagnostic does not match the current configuration or ', ...
    'production checkpoint (%s). Remove or replace the generated file ', ...
    'results/diagnostics/conditioning/k470_conditioning_reps1_3.mat, ', ...
    'then rerun examples/conditioning.m before exporting Table 6.'],detail);
end

function experiment = load_complete(filename)
saved = load(filename,'experiment');
experiment = saved.experiment;
assert(experiment.is_complete && experiment.repetitions==100 && ...
    all(experiment.completed_mask(:)) && ...
    all(~cellfun(@isempty,experiment.results(:))), ...
    'Expected a complete 100-repetition paper checkpoint: %s',filename);
end
