function reference = recompute_ackley_paraboloid_reference()
%RECOMPUTE_ACKLEY_PARABOLOID_REFERENCE Independent deterministic Case-4 solves.
% Experiments use the saved reference values.
d = 20;
m = d-1;
problem = ackley_problem(d,0.4*ones(d,1),20,0.1,1);
parameters = problem.metadata.ackley;
x0 = 0.3542;
initial = [x0*ones(m,1);m*x0^2];
options = optimoptions('fmincon','Display','off','Algorithm','sqp', ...
    'MaxIterations',4000,'MaxFunctionEvaluations',200000, ...
    'OptimalityTolerance',1e-13,'ConstraintTolerance',1e-13, ...
    'StepTolerance',1e-14,'FunctionTolerance',1e-14, ...
    'SpecifyObjectiveGradient',true,'SpecifyConstraintGradient',true);
[fmincon_vstar,fmincon_objective,exitflag,output,lambda,gradient] = fmincon( ...
    @(v) ackley_objective(v,parameters),initial,[],[],[],[],[],[], ...
    @paraboloid_constraint,options);
fsolve_options = optimoptions('fsolve','Display','off', ...
    'MaxIterations',4000,'MaxFunctionEvaluations',200000, ...
    'OptimalityTolerance',1e-14,'FunctionTolerance',1e-14, ...
    'StepTolerance',1e-14);
[kkt_point,~,kkt_exitflag,kkt_output] = fsolve( ...
    @(z)paraboloid_kkt(z,parameters), ...
    [fmincon_vstar;lambda.eqnonlin],fsolve_options);
vstar = kkt_point(1:d);
lambda_value = kkt_point(end);
objective_value = problem.E(vstar);
g_value = sum(vstar(1:m).^2)-vstar(d);
kkt_residual = paraboloid_kkt(kkt_point,parameters);
full = struct('vstar',vstar,'objective_value',objective_value, ...
    'g_value',g_value,'G_value',g_value^2, ...
    'feasibility_error',abs(g_value),'exitflag',exitflag, ...
    'firstorderopt',output.firstorderopt, ...
    'constraint_violation',output.constrviolation, ...
    'iterations',output.iterations,'func_count',output.funcCount, ...
    'kkt_residual_inf',norm(kkt_residual,Inf), ...
    'lambda_value',lambda_value,'lambda',lambda,'gradient',gradient, ...
    'initial_point',initial,'output',output, ...
    'fmincon_vstar',fmincon_vstar, ...
    'fmincon_objective_value',fmincon_objective, ...
    'fmincon_kkt_residual_inf',norm(gradient+ ...
    [2*fmincon_vstar(1:m);-1]*lambda.eqnonlin,Inf), ...
    'kkt_polish_exitflag',kkt_exitflag, ...
    'kkt_polish_iterations',kkt_output.iterations, ...
    'kkt_polish_func_count',kkt_output.funcCount, ...
    'kkt_polish_output',kkt_output,'kkt_polish_options',fsolve_options);

scan_interval = [-3,3];
scan_size = 60001;
x_scan = linspace(scan_interval(1),scan_interval(2),scan_size);
phi_values = symmetric_objective(x_scan,parameters,m);
[~,scan_index] = min(phi_values);
assert(scan_index>1 && scan_index<scan_size, ...
    'recompute_ackley_paraboloid_reference:BoundaryMinimum', ...
    'The symmetry scan minimum lies on the scan boundary.');
dx = x_scan(2)-x_scan(1);
bracket = x_scan(scan_index)+[-5,5]*dx;
one_d_options = optimset('Display','off','TolX',1e-14, ...
    'MaxIter',10000,'MaxFunEvals',10000);
[x_fminbnd,~,sym_exitflag,sym_output] = fminbnd( ...
    @(x)symmetric_objective(x,parameters,m),bracket(1),bracket(2), ...
    one_d_options);
derivative = @(x)symmetric_derivative(x,parameters,m);
root_bracket = x_fminbnd+[-20,20]*dx;
xstar = fzero(derivative,root_bracket, ...
    optimset('Display','off','TolX',1e-14,'MaxIter',10000, ...
    'MaxFunEvals',10000));
for polish_index=1:3
    h = 1e-6;
    derivative_slope = (derivative(xstar+h)-derivative(xstar-h))/(2*h);
    xstar = xstar-derivative(xstar)/derivative_slope;
end
vstar_sym = [xstar*ones(m,1);m*xstar^2];
sym_g = sum(vstar_sym(1:m).^2)-vstar_sym(d);
symmetric = struct('xstar',xstar,'vstar',vstar_sym, ...
    'objective_value',problem.E(vstar_sym),'g_value',sym_g, ...
    'G_value',sym_g^2,'feasibility_error',abs(sym_g), ...
    'directional_derivative',derivative(xstar), ...
    'fminbnd_xstar',x_fminbnd,'exitflag',sym_exitflag, ...
    'output',sym_output,'scan_interval',scan_interval, ...
    'scan_size',scan_size,'bracket',bracket);

reference = struct('full',full,'symmetric',symmetric, ...
    'max_coordinate_difference',norm(vstar-vstar_sym,Inf), ...
    'objective_difference',abs(objective_value-symmetric.objective_value), ...
    'full_symmetry_spread',max(vstar(1:m))-min(vstar(1:m)), ...
    'options',options);
end

function residual = paraboloid_kkt(z,parameters)
v = z(1:end-1);
lambda = z(end);
[~,gradient] = ackley_objective(v,parameters);
constraint_gradient = [2*v(1:end-1);-1];
constraint = sum(v(1:end-1).^2)-v(end);
residual = [gradient+lambda*constraint_gradient;constraint];
end

function [c,ceq,gradient_c,gradient_ceq] = paraboloid_constraint(v)
c = [];
ceq = sum(v(1:end-1).^2)-v(end);
gradient_c = [];
gradient_ceq = [2*v(1:end-1);-1];
end

function value = symmetric_objective(x,parameters,m)
V = [repmat(x,m,1);m*x.^2];
value = ackley_objective(V,parameters);
end

function value = symmetric_derivative(x,parameters,m)
v = [x*ones(m,1);m*x^2];
[~,gradient] = ackley_objective(v,parameters);
value = gradient.'*[ones(m,1);2*m*x];
end
